---
- name: Make sure no lock files are present
  become: true
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /var/lib/dpkg/lock
    - /var/lib/dpkg/lock-frontend

- name: Apt install nmap deps
  become: true
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  loop:
    - git
    - wget
    - build-essential
    - checkinstall
    - libpcre3-dev
    - libssl-dev
    - libpcap-dev
    - autoconf

- name: Mkdir $HOME/src/
  file: 
    state: directory
    path: "{{ ansible_env.HOME }}/src/" # usually /root/src/

- name: Git checkout nmap source
  git:
    repo: https://github.com/nmap/nmap.git
    dest: "{{ ansible_env.HOME }}/src/nmap"
    update: no
    #version: 

- name: Run nmap configure
  shell: bash -lc "./configure"
  args:
    chdir: "{{ ansible_env.HOME }}/src/nmap/"
    creates: /usr/local/bin/nmap

- name: Run nmap make
  shell: bash -lc "make"
  args:
    chdir: "{{ ansible_env.HOME }}/src/nmap/"
    creates: /usr/local/bin/nmap

- name: Run nmap make install
  shell: bash -lc "sudo make install"
  args:
    chdir: "{{ ansible_env.HOME }}/src/nmap/"
    creates: /usr/local/bin/nmap
