version: '3.8'

services:
  flyway:
    image: flyway/flyway:latest
    volumes:
       - ./flyway/sql:/flyway/sql
       - ./flyway/config:/flyway/conf  # Corrected volume path for Flyway configuration
    command: [ "migrate" ]  #
  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
      - "9092:9092"  # SonarQube Scanner listening port
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"  # Jenkins slave agent port
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false  # Disable initial setup wizard
  postgres:
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    image: postgres:10.1-alpine
    ports:
    - "5432:5432"
volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  jenkins_home:
