version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    command:
      [
        "-b",
        "0.0.0.0",
        "-Dkeycloak.profile.feature.upload_scripts=enabled",
        "-Dkeycloak.profile.feature.scripts=enabled",
      ]
